using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using VR147.AAA.Physics;using VR147.AAA.Physics.Golden;
namespace VR147.AAA.Editor{
 public static class M24EnglishAutomationV2{
  const string Scene="Assets/AAA/PhysicsCalibration/147VR_M24_EnglishCalibrationV2.unity",Root="Assets/AAA/PhysicsCalibration/RuntimeMeasurements/",Catalog="Assets/AAA/PhysicsCalibration/Golden/147VR_GoldenCatalog.asset";const float I=.75f,T=.5f;
  [Serializable]class D{public string side;public int repetitions;public float english;public float[] spinSpeedAtContact,spinSpeedAfterContact,spinAxisDotVertical,signedSpinAtContact,lateralDisplacement,objectPeakSpeed,firstFlightDistance,objectDirectionDot,postContactCueSpeed;public bool[] passed;}
  public static void CreateSceneAndExit(){var s=EditorSceneManager.OpenScene("Assets/AAA/PhysicsCalibration/147VR_M23_DrawCalibration.unity",OpenSceneMode.Single);foreach(var r in UnityEngine.Object.FindObjectsByType<M23DrawBatchRunner>())UnityEngine.Object.DestroyImmediate(r.gameObject);foreach(var r in UnityEngine.Object.FindObjectsByType<M24EnglishBatchRunner>())UnityEngine.Object.DestroyImmediate(r.gameObject);foreach(var r in UnityEngine.Object.FindObjectsByType<M24EnglishBatchRunnerV2>())UnityEngine.Object.DestroyImmediate(r.gameObject);Make("M24_V2_Left",-I,"english_left_runtime_measurements.json");Make("M24_V2_Right",I,"english_right_runtime_measurements.json");EditorSceneManager.SaveScene(s,Scene);AssetDatabase.SaveAssets();Debug.Log("[147VR M2.4 V2] SCENE READY");EditorApplication.Exit(0);}
  static void Make(string n,float e,string f){var g=new GameObject(n);var r=g.AddComponent<M24EnglishBatchRunnerV2>();var so=new SerializedObject(r);so.FindProperty("cueBall").objectReferenceValue=GameObject.Find("Red")?.GetComponent<Rigidbody>();so.FindProperty("objectBall").objectReferenceValue=GameObject.Find("Sphere.009")?.GetComponent<Rigidbody>();so.FindProperty("physicsAdapter").objectReferenceValue=UnityEngine.Object.FindAnyObjectByType<VR147.AAA.Cue.CuePhysicsAdapter>();so.FindProperty("physicsSetup").objectReferenceValue=UnityEngine.Object.FindAnyObjectByType<SnookerPhysicsSetup>();so.FindProperty("english").floatValue=e;so.FindProperty("outputFileName").stringValue=f;so.FindProperty("shotSpeed").floatValue=4;so.FindProperty("repetitions").intValue=5;so.ApplyModifiedPropertiesWithoutUndo();r.enabled=false;}
  public static void RunLeft(){Run("M24_V2_Left","english_left_runtime_measurements.json");}public static void RunRight(){Run("M24_V2_Right","english_right_runtime_measurements.json");}
  static void Run(string n,string f){Delete(f);EditorSceneManager.OpenScene(Scene,OpenSceneMode.Single);foreach(var r in UnityEngine.Object.FindObjectsByType<M24EnglishBatchRunnerV2>())r.enabled=false;var go=GameObject.Find(n);if(go==null)throw new InvalidOperationException(n+" missing");go.GetComponent<M24EnglishBatchRunnerV2>().enabled=true;EditorApplication.isPlaying=true;}
  public static void Build(){BuildOne("english_left_runtime_measurements.json","147VR-PHY-005","Left",-I);BuildOne("english_right_runtime_measurements.json","147VR-PHY-006","Right",I);Debug.Log("[147VR M2.4 V2 Golden] BUILD PASS | PHY-005 + PHY-006");EditorApplication.Exit(0);}
  static void BuildOne(string f,string id,string side,float input){var d=Load(f);Validate(d,side,input);float dist=Mean(d.firstFlightDistance),peak=Mean(d.objectPeakSpeed);string gp=$"Assets/AAA/PhysicsCalibration/Golden/{id}_{side}.asset",cp=$"Assets/AAA/PhysicsCalibration/{side}English_Runtime_Case.asset";var c=AssetDatabase.LoadAssetAtPath<ShotCalibrationCase>(cp)??ScriptableObject.CreateInstance<ShotCalibrationCase>();if(AssetDatabase.GetAssetPath(c)=="")AssetDatabase.CreateAsset(c,cp);c.type=side=="Left"?ShotCalibrationType.LeftEnglish:ShotCalibrationType.RightEnglish;c.power=1;c.side=input;c.vertical=0;c.expectedDistance=dist;c.tolerance=Mathf.Max(dist*T/100,1e-6f);c.expectedPeakSpeed=peak;c.peakSpeedTolerance=Mathf.Max(peak*T/100,1e-6f);c.validatePeakSpeed=true;var g=AssetDatabase.LoadAssetAtPath<PhysicsGoldenCase>(gp)??ScriptableObject.CreateInstance<PhysicsGoldenCase>();if(AssetDatabase.GetAssetPath(g)=="")AssetDatabase.CreateAsset(g,gp);Set(g,"caseId",id);Set(g,"revision",1);Set(g,"category",(int)PhysicsGoldenCategory.English);Set(g,"intent",$"Measured REAL {side} English runtime truth: vertical angular velocity, signed spin direction, cue lateral displacement observation and forward object travel.");Set(g,"calibrationCase",c);Set(g,"requirePass",true);Set(g,"sourceJsonPath",Root+f);Set(g,"sourceTimestampUtc",DateTime.UtcNow.ToString("O"));Set(g,"sourceScene",Scene);Set(g,"sourceUnityVersion",Application.unityVersion);Set(g,"sourceShotType","English");Set(g,"sourceRepetitionCount",5);Set(g,"measuredDistanceMean",dist);Set(g,"measuredDistanceStdDev",Std(d.firstFlightDistance,dist));Set(g,"measuredPeakSpeedMean",peak);Set(g,"measuredPeakSpeedStdDev",Std(d.objectPeakSpeed,peak));Set(g,"regressionTolerancePercent",T);Set(g,"measuredDistanceSamples",d.firstFlightDistance);Set(g,"measuredPeakSpeedSamples",d.objectPeakSpeed);EditorUtility.SetDirty(c);EditorUtility.SetDirty(g);AssetDatabase.SaveAssets();Update(g);}
  public static void Regression(){Reg("english_left_runtime_measurements.json","147VR-PHY-005",-I);Reg("english_right_runtime_measurements.json","147VR-PHY-006",I);Debug.Log("[147VR M2.4 Golden Regression] PASS | LEFT 5/5 | RIGHT 5/5 | tolerance=0.50%");EditorApplication.Exit(0);}
  [MenuItem("147 VR/Run M2.4 English Regression (No Exit)")]
  public static void RegressionNoExit(){try{Reg("english_left_runtime_measurements.json","147VR-PHY-005",-I);Reg("english_right_runtime_measurements.json","147VR-PHY-006",I);Debug.Log("[147VR M2.4 Golden Regression NoExit] PASS | LEFT 5/5 | RIGHT 5/5 | tolerance=0.50%");}catch(Exception ex){Debug.LogException(ex);}}
  static void Reg(string f,string id,float input){var d=Load(f);Validate(d,id.Contains("005")?"Left":"Right",input);var g=AssetDatabase.FindAssets("t:"+nameof(PhysicsGoldenCase)).Select(AssetDatabase.GUIDToAssetPath).Select(AssetDatabase.LoadAssetAtPath<PhysicsGoldenCase>).FirstOrDefault(x=>x!=null&&x.CaseId==id);if(g==null)throw new InvalidOperationException(id+" missing");for(int i=0;i<5;i++){var r=PhysicsGoldenEvaluator.Evaluate(g,d.firstFlightDistance[i],d.objectPeakSpeed[i]);if(!r.passed)throw new InvalidOperationException(id+" regression fail "+(i+1));Debug.Log($"[147VR M2.4 Golden Regression] {id} rep={i+1}/5 PASS | spin={d.spinSpeedAtContact[i]:F6} signed={d.signedSpinAtContact[i]:F6} axisDot={d.spinAxisDotVertical[i]:F6} cueLateral={d.lateralDisplacement[i]:F9}");}}
  static D Load(string f){var p=Project(Root+f);if(!File.Exists(p))throw new FileNotFoundException(f,p);return JsonUtility.FromJson<D>(File.ReadAllText(p));}
  static void Validate(D d,string side,float input){if(d==null||d.repetitions!=5||d.passed?.Length!=5||d.spinSpeedAtContact?.Length!=5)throw new InvalidOperationException(side+" JSON incomplete");if(Mathf.Abs(d.english-input)>.0001f)throw new InvalidOperationException(side+" input mismatch");if(d.side!=(side=="Left"?"LEFT":"RIGHT"))throw new InvalidOperationException(side+" side mismatch");for(int i=0;i<5;i++){bool sign=side=="Left"?d.signedSpinAtContact[i]>0:d.signedSpinAtContact[i]<0;if(!d.passed[i]||d.spinSpeedAtContact[i]<=.05f||Mathf.Abs(d.spinAxisDotVertical[i])<.9f||!sign||d.objectDirectionDot[i]<=0)throw new InvalidOperationException(side+" acceptance failed "+(i+1));}}
  static void Update(PhysicsGoldenCase g){var c=AssetDatabase.LoadAssetAtPath<PhysicsGoldenCatalog>(Catalog);if(c==null)throw new InvalidOperationException("catalog missing");var so=new SerializedObject(c);var p=so.FindProperty("cases");for(int i=0;i<p.arraySize;i++)if((p.GetArrayElementAtIndex(i).objectReferenceValue as PhysicsGoldenCase)?.CaseId==g.CaseId){p.GetArrayElementAtIndex(i).objectReferenceValue=g;so.ApplyModifiedPropertiesWithoutUndo();AssetDatabase.SaveAssets();return;}p.arraySize++;p.GetArrayElementAtIndex(p.arraySize-1).objectReferenceValue=g;so.ApplyModifiedPropertiesWithoutUndo();AssetDatabase.SaveAssets();}
  static void Delete(string f){var p=Project(Root+f);if(File.Exists(p))File.Delete(p);}static string Project(string p)=>Path.Combine(Directory.GetParent(Application.dataPath).FullName,p.Replace('/',Path.DirectorySeparatorChar));static float Mean(float[] a)=>a.Average();static float Std(float[] a,float m)=>Mathf.Sqrt(a.Select(x=>(x-m)*(x-m)).Average());static void Set(UnityEngine.Object t,string n,object v){var so=new SerializedObject(t);var p=so.FindProperty(n);if(v is string s)p.stringValue=s;else if(v is int i)p.intValue=i;else if(v is float f)p.floatValue=f;else if(v is bool b)p.boolValue=b;else if(v is UnityEngine.Object o)p.objectReferenceValue=o;else if(v is float[] a){p.arraySize=a.Length;for(int j=0;j<a.Length;j++)p.GetArrayElementAtIndex(j).floatValue=a[j];}so.ApplyModifiedPropertiesWithoutUndo();}
 }
}
