using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEditor;
namespace VR147.AAA.Editor
{
 public static class M4BallCollisionRuntimeRunner
 {
  [Serializable] class Sample { public string contactFamily; public float referenceAngleDeg,measuredNormalAngleDeg,preSpeed,targetPostSpeed,strikerPostSpeed,energyRatio,preRelNormalSpeed,postRelNormalSpeed,deltaVelocitySum; public bool collisionObserved,impulseObserved; }
  [Serializable] class Output { public string timestampUtc,unityVersion,caseName,authority; public int repetitions; public Sample[] samples; }
  readonly struct CaseSpec { public readonly string name,label; public readonly float angle,offset; public CaseSpec(string n,string l,float a,float o){name=n;label=l;angle=a;offset=o;} }
  const float R=.028575f,Speed=2.5f,Dt=.005f,Tol=.001f,MinResponse=.005f;
  static readonly CaseSpec[] Cases={new("full","Full Ball",0f,0f),new("threequarter","3/4 Ball",14.5f,2f*R*Mathf.Sin(14.5f*Mathf.Deg2Rad)),new("half","1/2 Ball",30f,2f*R*Mathf.Sin(30f*Mathf.Deg2Rad)),new("quarter","1/4 Ball",49f,2f*R*Mathf.Sin(49f*Mathf.Deg2Rad)),new("eighth","1/8 Ball",60f,2f*R*Mathf.Sin(60f*Mathf.Deg2Rad)),new("thin","Thin / Edge",63f,2f*R*Mathf.Sin(63f*Mathf.Deg2Rad))};
  public static void RunAll(){var root=Directory.GetParent(Application.dataPath).FullName;var dir=Path.Combine(root,"Assets/AAA/PhysicsCalibration/RuntimeMeasurements");Directory.CreateDirectory(dir);var old=UnityEngine.Physics.autoSimulation;UnityEngine.Physics.autoSimulation=false;try{foreach(var c in Cases)RunCase(c,dir);Debug.Log("[147VR M4] COMPLETE | 30 REAL ball-collision samples generated");}finally{UnityEngine.Physics.autoSimulation=old;}if(Application.isBatchMode)EditorApplication.Exit(0);}
  static void RunCase(CaseSpec c,string dir){var ss=new List<Sample>(5);for(int rep=0;rep<5;rep++){var t=Create("M4_Target",Vector3.zero);var s=Create("M4_Striker",new Vector3(-1f,0,c.offset));var tr=t.GetComponent<Rigidbody>();var sr=s.GetComponent<Rigidbody>();tr.linearVelocity=Vector3.zero;sr.linearVelocity=Vector3.right*Speed;UnityEngine.Physics.SyncTransforms();float measured=0,tPost=0,sPost=0,energy=0,preRel=0,postRel=0,deltaV=0;bool observed=false;for(int i=0;i<1200;i++){var preT=tr.linearVelocity;var preS=sr.linearVelocity;var preDelta=tr.position-sr.position;var preDist=preDelta.magnitude;var preN=preDist>1e-7f?preDelta/preDist:Vector3.right;preRel=Vector3.Dot(preS-preT,preN);UnityEngine.Physics.Simulate(Dt);var delta=tr.position-sr.position;var dist=delta.magnitude;var n=dist>1e-7f?delta/dist:preN;postRel=Vector3.Dot(sr.linearVelocity-tr.linearVelocity,n);deltaV=(tr.linearVelocity-preT).magnitude+(sr.linearVelocity-preS).magnitude;if(dist<=2f*R+Tol&&preRel>0f&&deltaV>MinResponse){observed=true;measured=Mathf.Abs(Vector3.SignedAngle(Vector3.right,preN,Vector3.up));tPost=tr.linearVelocity.magnitude;sPost=sr.linearVelocity.magnitude;energy=(tPost*tPost+sPost*sPost)/(Speed*Speed);break;}}UnityEngine.Object.DestroyImmediate(t);UnityEngine.Object.DestroyImmediate(s);if(!observed)throw new InvalidOperationException($"M4 {c.name} rep={rep+1}/5 collision response not observed/validated");ss.Add(new Sample{contactFamily=c.label,referenceAngleDeg=c.angle,measuredNormalAngleDeg=measured,preSpeed=Speed,targetPostSpeed=tPost,strikerPostSpeed=sPost,energyRatio=energy,preRelNormalSpeed=preRel,postRelNormalSpeed=postRel,deltaVelocitySum=deltaV,collisionObserved=true,impulseObserved=true});Debug.Log($"[147VR M4] REAL {c.label} rep={rep+1}/5 | normal={measured:F3} | targetSpeed={tPost:F4} | strikerSpeed={sPost:F4} | energy={energy:F4} | preRelN={preRel:F4} | postRelN={postRel:F4} | deltaV={deltaV:F4} | COLLISION=True");}File.WriteAllText(Path.Combine(dir,$"m4_{c.name}_runtime_measurements.json"),JsonUtility.ToJson(new Output{timestampUtc=DateTime.UtcNow.ToString("O"),unityVersion=Application.unityVersion,caseName=c.label,authority="Unity PhysX runtime; contact+response observer",repetitions=5,samples=ss.ToArray()},true));Debug.Log($"[147VR M4] REAL DATA SAVED | {c.label}");}
  static GameObject Create(string name,Vector3 p){var g=GameObject.CreatePrimitive(PrimitiveType.Sphere);g.name=name;g.transform.position=p;g.transform.localScale=Vector3.one*(2f*R);var rb=g.AddComponent<Rigidbody>();rb.useGravity=false;rb.mass=.17f;rb.collisionDetectionMode=CollisionDetectionMode.ContinuousDynamic;rb.interpolation=RigidbodyInterpolation.None;return g;}
 }
}
