using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using VR147.AAA.Physics.Golden;
namespace VR147.AAA.Editor
{
 public static class M4GoldenCertificationAutomation
 {
  const string Dir="Assets/AAA/PhysicsCalibration/RuntimeMeasurements",GoldenDir="Assets/AAA/PhysicsCalibration/Golden";
  static readonly (string file,string id,string label)[] Cases={("m4_full_runtime_measurements.json","147VR-PHY-014","Full Ball"),("m4_threequarter_runtime_measurements.json","147VR-PHY-015","3/4 Ball"),("m4_half_runtime_measurements.json","147VR-PHY-016","1/2 Ball"),("m4_quarter_runtime_measurements.json","147VR-PHY-017","1/4 Ball"),("m4_eighth_runtime_measurements.json","147VR-PHY-018","1/8 Ball"),("m4_thin_runtime_measurements.json","147VR-PHY-019","Thin / Edge")};
  [Serializable] class Measurement{public string timestampUtc,unityVersion,caseName;public int repetitions;public Sample[] samples;} [Serializable] class Sample{public string contactFamily;public float referenceAngleDeg,measuredNormalAngleDeg,targetPostSpeed,strikerPostSpeed,energyRatio,deltaVelocitySum,preRelNormalSpeed,postRelNormalSpeed;public bool collisionObserved,impulseObserved;}
  [MenuItem("147VR/AAA/Physics/M4/Build And Regress Goldens")]
  public static void BuildAndRegress(){Ensure();var list=new System.Collections.Generic.List<M4BallCollisionGolden>();foreach(var c in Cases){var path=Path.Combine(Directory.GetParent(Application.dataPath).FullName,Dir,c.file);var d=JsonUtility.FromJson<Measurement>(File.ReadAllText(path));Validate(d,c.label);var means=d.samples.Select(x=>x).ToArray();var g=ScriptableObject.CreateInstance<M4BallCollisionGolden>();g.caseId=c.id;g.family=c.label;g.sourceJsonPath=Dir+"/"+c.file;g.sourceTimestampUtc=d.timestampUtc;g.sourceUnityVersion=d.unityVersion;g.referenceAngleDeg=means[0].referenceAngleDeg;g.repetitions=5;g.tolerancePercent=.5f;g.measuredNormalSamples=means.Select(x=>x.measuredNormalAngleDeg).ToArray();g.targetSpeedSamples=means.Select(x=>x.targetPostSpeed).ToArray();g.strikerSpeedSamples=means.Select(x=>x.strikerPostSpeed).ToArray();g.energyRatioSamples=means.Select(x=>x.energyRatio).ToArray();g.deltaVelocitySamples=means.Select(x=>x.deltaVelocitySum).ToArray();g.preRelNormalSamples=means.Select(x=>x.preRelNormalSpeed).ToArray();g.postRelNormalSamples=means.Select(x=>x.postRelNormalSpeed).ToArray();g.measuredNormalMean=Mean(g.measuredNormalSamples);g.measuredNormalStd=Std(g.measuredNormalSamples,g.measuredNormalMean);g.targetSpeedMean=Mean(g.targetSpeedSamples);g.targetSpeedStd=Std(g.targetSpeedSamples,g.targetSpeedMean);g.strikerSpeedMean=Mean(g.strikerSpeedSamples);g.strikerSpeedStd=Std(g.strikerSpeedSamples,g.strikerSpeedMean);g.energyRatioMean=Mean(g.energyRatioSamples);g.energyRatioStd=Std(g.energyRatioSamples,g.energyRatioMean);g.deltaVelocityMean=Mean(g.deltaVelocitySamples);g.deltaVelocityStd=Std(g.deltaVelocitySamples,g.deltaVelocityMean);g.preRelNormalMean=Mean(g.preRelNormalSamples);g.postRelNormalMean=Mean(g.postRelNormalSamples);var asset=GoldenDir+"/"+c.id.Replace("147VR-PHY-", "147VR-PHY-")+"_"+Safe(c.label)+".asset";if(AssetDatabase.LoadAssetAtPath<M4BallCollisionGolden>(asset)!=null)AssetDatabase.DeleteAsset(asset);AssetDatabase.CreateAsset(g,asset);list.Add(g);}
  var cat=AssetDatabase.LoadAssetAtPath<M4BallCollisionGoldenCatalog>(GoldenDir+"/147VR_M4_GoldenCatalog.asset");if(cat==null){cat=ScriptableObject.CreateInstance<M4BallCollisionGoldenCatalog>();AssetDatabase.CreateAsset(cat,GoldenDir+"/147VR_M4_GoldenCatalog.asset");}cat.cases=list;EditorUtility.SetDirty(cat);AssetDatabase.SaveAssets();foreach(var c in list)Regression(c);if(!cat.Validate())throw new InvalidOperationException("M4 Golden catalog validation failed.");Debug.Log("[147VR M4 Golden] CERTIFIED | 6/6 cases | 30/30 REAL samples");}
  static void Validate(Measurement d,string label){if(d==null||d.repetitions!=5||d.samples==null||d.samples.Length!=5)throw new InvalidOperationException("Invalid M4 JSON: "+label);if(d.samples.Any(x=>!x.collisionObserved||!x.impulseObserved||x.deltaVelocitySum<=.005f||x.targetPostSpeed<=0f))throw new InvalidOperationException("M4 REAL response validation failed: "+label);}
  static void Regression(M4BallCollisionGolden g){for(int i=0;i<5;i++){if(Mathf.Abs(g.measuredNormalSamples[i]-g.measuredNormalMean)>.01f)throw new InvalidOperationException(g.caseId+" angle regression failed");Check(g.targetSpeedSamples[i],g.targetSpeedMean,g.caseId+" targetSpeed");Check(g.strikerSpeedSamples[i],g.strikerSpeedMean,g.caseId+" strikerSpeed");Check(g.energyRatioSamples[i],g.energyRatioMean,g.caseId+" energy");Check(g.deltaVelocitySamples[i],g.deltaVelocityMean,g.caseId+" deltaV");}Debug.Log($"[147VR M4 Golden Regression] {g.caseId} PASS 5/5");}
  static void Check(float v,float m,string n){if(Mathf.Abs(v-m)>Mathf.Max(.0001f,Mathf.Abs(m)*.005f))throw new InvalidOperationException(n+" regression failed");}
  static float Mean(float[] a)=>a.Average();static float Std(float[] a,float m){float s=0;foreach(var v in a){var d=v-m;s+=d*d;}return Mathf.Sqrt(s/a.Length);}static void Ensure(){if(!AssetDatabase.IsValidFolder(GoldenDir))AssetDatabase.CreateFolder("Assets/AAA/PhysicsCalibration","Golden");}static string Safe(string s)=>s.Replace("/","_").Replace(" ","_");
 }
}
