using NUnit.Framework;
using M5Rules;
using UnityEngine;

public sealed class M5PostCueReliabilityTests
{
    private static void NewBall(Transform parent,string name){var go=new GameObject(name);go.transform.SetParent(parent);}
    private static GameObject MakeRig(out SnookerBallTracker tracker,out SnookerScoreManager score,out SnookerTurnManager turns){var root=new GameObject("M5PostCueRig");tracker=root.AddComponent<SnookerBallTracker>();tracker.tableRoot=root.transform;NewBall(root.transform,"White_CueBall");NewBall(root.transform,"Red_01");NewBall(root.transform,"Red_02");score=root.AddComponent<SnookerScoreManager>();turns=root.AddComponent<SnookerTurnManager>();tracker.Refresh();score.Initialize();return root;}
    [Test] public void Builder_Rejects_Sphere009_Without_CueIdentity(){var root=new GameObject("Sphere009Only");try{var sphere=new GameObject("Sphere.009");sphere.transform.SetParent(root.transform);var tracker=root.AddComponent<SnookerBallTracker>();tracker.tableRoot=root.transform;tracker.Refresh();Assert.Throws<System.InvalidOperationException>(()=>new M5ShotObservationBuilder(tracker));}finally{Object.DestroyImmediate(root);}}
    [Test] public void Applier_Rejects_Sphere009_Without_CueIdentity(){var root=new GameObject("Sphere009Applier");try{var sphere=new GameObject("Sphere.009");sphere.transform.SetParent(root.transform);var tracker=root.AddComponent<SnookerBallTracker>();tracker.tableRoot=root.transform;var score=root.AddComponent<SnookerScoreManager>();var turns=root.AddComponent<SnookerTurnManager>();tracker.Refresh();score.Initialize();Assert.Throws<System.InvalidOperationException>(()=>new M5ShotTransactionApplier(score,tracker,turns));}finally{Object.DestroyImmediate(root);}}
    [Test] public void NotificationFault_IsReported_Without_RollingBack_CommittedState(){SnookerBallTracker tracker;SnookerScoreManager score;SnookerTurnManager turns;var root=MakeRig(out tracker,out score,out turns);try{var builder=new M5ShotObservationBuilder(tracker);var start=builder.CaptureStartState(1,score,turns);var red=tracker.FindBall("Red");var observation=builder.Build(start,red,true,true,new[]{red});var decision=M5SnookerRulesEngine.Evaluate(observation);var applier=new M5ShotTransactionApplier(score,tracker,turns);int turnNotifications=0;score.ScoresChanged+=()=>{throw new System.InvalidOperationException("Injected score notification failure");};turns.TurnChanged+=_=>turnNotifications++;Assert.IsFalse(applier.Apply(decision,start));Assert.AreEqual(1,score.Player1Score);Assert.IsTrue(red.potted);Assert.AreEqual(1,turnNotifications);}finally{Object.DestroyImmediate(root);}}
}
