using System;using System.Collections.Generic;using System.IO;using UnityEngine;using VR147.AAA.Cue;
namespace VR147.AAA.Physics{
 public sealed class M24EnglishBatchRunnerV2:MonoBehaviour{
  [SerializeField]Rigidbody cueBall,objectBall;[SerializeField]CuePhysicsAdapter physicsAdapter;[SerializeField]SnookerPhysicsSetup physicsSetup;[SerializeField]float english=.75f,shotSpeed=4f;[SerializeField]int repetitions=5;[SerializeField]string outputFileName="english_left_runtime_measurements.json";const float Dt=.02f;readonly List<Sample> samples=new();Vector3 cueStart,objectStart,direction,lateral;
  [Serializable]class Sample{public float cueSpeedAtContact,spinSpeedAtContact,spinSpeedAfterContact,spinAxisDotVertical,signedSpinAtContact,lateralDisplacement,objectPeakSpeed,firstFlightDistance,objectDirectionDot,postContactCueSpeed;public Vector3 angularVelocityAtContact,angularVelocityAfterContact,cueVelocityAtContact,cueVelocityAfterContact,objectVelocityAtContact;public bool passed;}
  [Serializable]class Output{public string timestampUtc,caseType="English",side,scene,unityVersion;public int repetitions;public float shotSpeed,english;public float[] cueSpeedAtContact,spinSpeedAtContact,spinSpeedAfterContact,spinAxisDotVertical,signedSpinAtContact,lateralDisplacement,objectPeakSpeed,firstFlightDistance,objectDirectionDot,postContactCueSpeed;public Vector3[] angularVelocityAtContact,angularVelocityAfterContact,cueVelocityAtContact,cueVelocityAfterContact,objectVelocityAtContact;public bool[] passed;}
  void Start(){physicsSetup??=FindAnyObjectByType<SnookerPhysicsSetup>();cueBall??=GameObject.Find("Red")?.GetComponent<Rigidbody>();objectBall??=GameObject.Find("Sphere.009")?.GetComponent<Rigidbody>();physicsAdapter??=FindAnyObjectByType<CuePhysicsAdapter>();if(physicsSetup==null||cueBall==null||objectBall==null||physicsAdapter==null)throw new InvalidOperationException("M2.4 missing physics refs");physicsSetup.EnsurePhysics();var cc=cueBall.GetComponent<SphereCollider>();var oc=objectBall.GetComponent<SphereCollider>();if(cc==null||oc==null)throw new InvalidOperationException("M2.4 balls need SphereCollider");var c=physicsSetup.TableBounds.center;cueStart=new Vector3(c.x+.30f,physicsSetup.SurfaceTopY+cc.radius,c.z-.325f);objectStart=new Vector3(c.x+.30f,physicsSetup.SurfaceTopY+oc.radius,c.z+.325f);direction=objectStart-cueStart;direction.y=0;direction.Normalize();lateral=Vector3.Cross(Vector3.up,direction).normalized;Run();}
  void Run(){var old=UnityEngine.Physics.simulationMode;UnityEngine.Physics.simulationMode=SimulationMode.Script;try{for(int i=0;i<repetitions;i++)One(i);Persist();Debug.Log($"[147VR M2.4 V2] REAL {Side()} COMPLETE | {repetitions}/{repetitions} | input={english:F2}");}finally{UnityEngine.Physics.simulationMode=old;}enabled=false;
#if UNITY_EDITOR
   UnityEditor.EditorApplication.Exit(0);
#else
   Application.Quit(0);
#endif
  }
  void One(int rep){cueBall.position=cueStart;objectBall.position=objectStart;cueBall.linearVelocity=Vector3.zero;cueBall.angularVelocity=Vector3.zero;objectBall.linearVelocity=Vector3.zero;objectBall.angularVelocity=Vector3.zero;UnityEngine.Physics.SyncTransforms();var probe=cueBall.GetComponent<M24ContactProbeV2>()??cueBall.gameObject.AddComponent<M24ContactProbeV2>();probe.Target=objectBall;probe.ResetCapture();physicsAdapter.Configure(cueBall);if(!physicsAdapter.Apply(new CueShotData(direction,cueBall.position,1f,shotSpeed),new Vector2(english,0)))throw new InvalidOperationException("M2.4 adapter rejected English");float peak=0;int contactStep=-1;for(int step=0;step<600;step++){UnityEngine.Physics.Simulate(Dt);peak=Mathf.Max(peak,objectBall.linearVelocity.magnitude);if(!probe.Contacted&&Vector3.Distance(cueBall.position,objectBall.position)<=cueBall.GetComponent<SphereCollider>().radius+objectBall.GetComponent<SphereCollider>().radius+0.0005f)probe.CaptureManual(cueBall,objectBall);if(probe.Contacted&&contactStep<0)contactStep=step;if(probe.Contacted&&step>=contactStep+30)break;}if(!probe.Contacted)throw new InvalidOperationException($"M2.4 {Side()} shot {rep+1} no contact");Vector3 av=probe.CueAngularVelocityAtContact,after=cueBall.angularVelocity;float spin=av.magnitude,spinAfter=after.magnitude,axis=spin>1e-6f?Vector3.Dot(av.normalized,Vector3.up):0;float signed=Vector3.Dot(av,Vector3.up);float lateralDisp=Vector3.Dot(cueBall.position-probe.CuePositionAtContact,lateral);Vector3 ov=probe.ObjectVelocityAtContact;float objDot=ov.sqrMagnitude>1e-8f?Vector3.Dot(ov.normalized,direction):0;float first=Vector3.Distance(objectStart,objectBall.position);float post=cueBall.linearVelocity.magnitude;bool sideSign=english<0?signed>0:signed<0;bool pass=spin>.05f&&spinAfter>.05f&&Mathf.Abs(axis)>.9f&&objDot>0&&sideSign;samples.Add(new Sample{cueSpeedAtContact=probe.CueVelocityAtContact.magnitude,cueVelocityAtContact=probe.CueVelocityAtContact,cueVelocityAfterContact=cueBall.linearVelocity,objectVelocityAtContact=ov,angularVelocityAtContact=av,angularVelocityAfterContact=after,spinSpeedAtContact=spin,spinSpeedAfterContact=spinAfter,spinAxisDotVertical=axis,signedSpinAtContact=signed,lateralDisplacement=lateralDisp,objectPeakSpeed=peak,firstFlightDistance=first,objectDirectionDot=objDot,postContactCueSpeed=post,passed=pass});Debug.Log($"[147VR M2.4 V2] {Side()} rep={rep+1}/{repetitions} spin={spin:F6} signed={signed:F6} axisDot={axis:F6} cueLateral={lateralDisp:F9} objectDot={objDot:F6} peak={peak:F6} {(pass?"PASS":"FAIL")}");if(!pass)throw new InvalidOperationException($"M2.4 {Side()} acceptance failed rep {rep+1}");}
  string Side()=>english<0?"LEFT":"RIGHT";void Persist(){string root=Directory.GetParent(Application.dataPath).FullName,dir=Path.Combine(root,"Assets/AAA/PhysicsCalibration/RuntimeMeasurements");Directory.CreateDirectory(dir);var o=new Output{timestampUtc=DateTime.UtcNow.ToString("O"),side=Side(),scene="Assets/AAA/PhysicsCalibration/147VR_M24_EnglishCalibrationV2.unity",unityVersion=Application.unityVersion,repetitions=samples.Count,shotSpeed=shotSpeed,english=english,cueSpeedAtContact=A(s=>s.cueSpeedAtContact),spinSpeedAtContact=A(s=>s.spinSpeedAtContact),spinSpeedAfterContact=A(s=>s.spinSpeedAfterContact),spinAxisDotVertical=A(s=>s.spinAxisDotVertical),signedSpinAtContact=A(s=>s.signedSpinAtContact),lateralDisplacement=A(s=>s.lateralDisplacement),objectPeakSpeed=A(s=>s.objectPeakSpeed),firstFlightDistance=A(s=>s.firstFlightDistance),objectDirectionDot=A(s=>s.objectDirectionDot),postContactCueSpeed=A(s=>s.postContactCueSpeed),angularVelocityAtContact=V(s=>s.angularVelocityAtContact),angularVelocityAfterContact=V(s=>s.angularVelocityAfterContact),cueVelocityAtContact=V(s=>s.cueVelocityAtContact),cueVelocityAfterContact=V(s=>s.cueVelocityAfterContact),objectVelocityAtContact=V(s=>s.objectVelocityAtContact),passed=B(s=>s.passed)};File.WriteAllText(Path.Combine(dir,outputFileName),JsonUtility.ToJson(o,true));UnityEditor.AssetDatabase.Refresh();}float[] A(Func<Sample,float>f){var a=new float[samples.Count];for(int i=0;i<a.Length;i++)a[i]=f(samples[i]);return a;}Vector3[] V(Func<Sample,Vector3>f){var a=new Vector3[samples.Count];for(int i=0;i<a.Length;i++)a[i]=f(samples[i]);return a;}bool[] B(Func<Sample,bool>f){var a=new bool[samples.Count];for(int i=0;i<a.Length;i++)a[i]=f(samples[i]);return a;}
 }
 public sealed class M24ContactProbeV2:MonoBehaviour{public Rigidbody Target;public bool Contacted{get;private set;}public Vector3 CueVelocityAtContact{get;private set;}public Vector3 ObjectVelocityAtContact{get;private set;}public Vector3 CueAngularVelocityAtContact{get;private set;}public Vector3 CuePositionAtContact{get;private set;}public Vector3 ObjectPositionAtContact{get;private set;}public void ResetCapture(){Contacted=false;CueVelocityAtContact=Vector3.zero;ObjectVelocityAtContact=Vector3.zero;CueAngularVelocityAtContact=Vector3.zero;CuePositionAtContact=Vector3.zero;ObjectPositionAtContact=Vector3.zero;}public void CaptureManual(Rigidbody cue,Rigidbody target){if(Contacted)return;Contacted=true;CueVelocityAtContact=cue.linearVelocity;CueAngularVelocityAtContact=cue.angularVelocity;CuePositionAtContact=cue.position;ObjectVelocityAtContact=target.linearVelocity;ObjectPositionAtContact=target.position;}void OnCollisionEnter(Collision c){if(Contacted||Target==null||c.rigidbody!=Target)return;Contacted=true;var rb=GetComponent<Rigidbody>();CueVelocityAtContact=rb.linearVelocity;CueAngularVelocityAtContact=rb.angularVelocity;CuePositionAtContact=transform.position;ObjectVelocityAtContact=Target.linearVelocity;ObjectPositionAtContact=Target.position;}}
}
